#!/usr/bin/env python3

"""
GCD Build Examples - Rust REST API

Examples demonstrating how to use the GCD REST API client and builders
to generate GCD files, replacing the original BuildGCD.py workflow.
"""

import json
import logging
from gcd_rest_client import GCDRestClient, GCDBuilder, GCDAPIConfig, APIError

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def example_1_basic_gcd_generation():
    """Example 1: Basic GCD generation"""
    logger.info("Example 1: Basic GCD Generation")
    
    # Configure API access
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    
    # Create client
    client = GCDRestClient(config)
    
    # Generate GCD for specific run
    try:
        gcd_collection = client.generate_gcd_collection(run_number=137292)
        
        logger.info(f"Generated GCD collection: {gcd_collection['collection_id']}")
        logger.info(f"  Calibrations: {len(gcd_collection['calibrations'])}")
        logger.info(f"  Geometry: {len(gcd_collection['geometry'])}")
        logger.info(f"  Detector Status: {len(gcd_collection['detector_status'])}")
        
    except APIError as e:
        logger.error(f"Failed to generate GCD: {e}")


def example_2_save_gcd_to_file():
    """Example 2: Generate and save GCD to JSON file"""
    logger.info("\nExample 2: Save GCD to File")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    builder = GCDBuilder(client)
    
    # Build and save
    if builder.build_and_save(run_number=137292, output_file="gcd_137292.json"):
        logger.info("GCD saved to gcd_137292.json")
        
        # Verify file
        with open("gcd_137292.json") as f:
            data = json.load(f)
            logger.info(f"File contains {len(data['calibrations'])} calibrations")
    else:
        logger.error("Failed to build GCD")


def example_3_get_gcd_summary():
    """Example 3: Get summary statistics for a run's GCD"""
    logger.info("\nExample 3: Get GCD Summary")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    builder = GCDBuilder(client)
    
    # Get summary
    summary = builder.get_summary(run_number=137292)
    if summary:
        logger.info(f"GCD Summary for run {summary['run_number']}:")
        logger.info(f"  Collection ID: {summary['collection_id']}")
        logger.info(f"  Calibrations: {summary['num_calibrations']}")
        logger.info(f"  Geometry: {summary['num_geometry']}")
        logger.info(f"  Detector Status: {summary['num_detector_status']}")
        logger.info(f"  Generated at: {summary['generated_at']}")
        logger.info(f"  Generated by: {summary['generated_by']}")


def example_4_access_gcd_components():
    """Example 4: Access individual GCD components"""
    logger.info("\nExample 4: Access GCD Components")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    
    try:
        # Get all calibrations
        calibrations = client.get_calibrations()
        logger.info(f"Total calibrations in database: {len(calibrations)}")
        if calibrations:
            first_cal = calibrations[0]
            logger.info(f"  Example: DOM {first_cal['dom_id']} "
                       f"(FADC gain: {first_cal['domcal']['fadc_gain']})")
        
        # Get specific calibration
        cal = client.get_calibration(dom_id=161)
        if cal:
            logger.info(f"Calibration for DOM 161: "
                       f"FADC gain = {cal['domcal']['fadc_gain']}")
        
        # Get all geometry
        geometry = client.get_geometry()
        logger.info(f"Total geometry entries: {len(geometry)}")
        if geometry:
            first_geom = geometry[0]
            logger.info(f"  Example: String {first_geom['string']} "
                       f"Position {first_geom['position']} "
                       f"at ({first_geom['location']['x']}, "
                       f"{first_geom['location']['y']}, "
                       f"{first_geom['location']['z']})")
        
        # Get detector statuses
        statuses = client.get_detector_statuses()
        logger.info(f"Total detector statuses: {len(statuses)}")
        
        # Count operational vs bad
        operational = sum(1 for s in statuses if not s['is_bad'])
        bad = sum(1 for s in statuses if s['is_bad'])
        logger.info(f"  Operational: {operational}, Bad: {bad}")
        
    except APIError as e:
        logger.error(f"Failed to access components: {e}")


def example_5_run_specific_data():
    """Example 5: Get run-specific data (snow height, etc.)"""
    logger.info("\nExample 5: Run-Specific Data")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    
    run_number = 137292
    
    try:
        # Get snow height
        snow = client.get_snow_height(run_number)
        if snow:
            logger.info(f"Run {run_number} snow height: {snow['height']} m")
        else:
            logger.info(f"No snow height data for run {run_number}")
        
        # Get configuration data
        try:
            noise_config = client.get_configuration("noise_rate_1_61")
            if noise_config:
                logger.info(f"Noise rate config: {noise_config['value']}")
        except APIError:
            logger.info("No noise rate configuration found")
        
    except APIError as e:
        logger.error(f"Failed to get run data: {e}")


def example_6_batch_operations():
    """Example 6: Batch operations and data updates"""
    logger.info("\nExample 6: Batch Operations")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    
    try:
        # Update snow height for multiple runs
        runs = [137292, 137293, 137294]
        heights = [2.5, 2.6, 2.7]
        
        for run, height in zip(runs, heights):
            try:
                result = client.update_snow_height(run, height)
                logger.info(f"Updated run {run} snow height to {height} m")
            except APIError as e:
                logger.warning(f"Failed to update run {run}: {e}")
        
        # Create configuration entry
        config_data = {
            "rate_hz": 1386.35,
            "stddev_hz": 11.83,
            "timestamp": "2025-12-21T10:00:00Z"
        }
        result = client.create_configuration(
            key="noise_rate_1_61",
            value=config_data
        )
        logger.info(f"Created configuration: noise_rate_1_61")
        
    except APIError as e:
        logger.error(f"Batch operation failed: {e}")


def example_7_error_handling():
    """Example 7: Error handling and validation"""
    logger.info("\nExample 7: Error Handling")
    
    config = GCDAPIConfig(
        api_url="http://invalid-url:8080",
        bearer_token="invalid-token"
    )
    client = GCDRestClient(config)
    
    # Try to generate GCD - will fail with connection error
    try:
        gcd = client.generate_gcd_collection(137292)
    except APIError as e:
        logger.error(f"Expected error: {e}")
    
    # Proper error handling pattern
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="valid-token"
    )
    client = GCDRestClient(config)
    
    if not client.health_check():
        logger.error("API server is not responding")
        return
    
    if not client.verify_token():
        logger.error("Authentication token is invalid")
        return
    
    try:
        gcd = client.generate_gcd_collection(137292)
        logger.info(f"Successfully generated GCD collection: {gcd['collection_id']}")
    except APIError as e:
        logger.error(f"Failed to generate GCD: {e}")


def example_8_retrieve_previous_collection():
    """Example 8: Retrieve a previously generated GCD collection"""
    logger.info("\nExample 8: Retrieve Previous Collection")
    
    config = GCDAPIConfig(
        api_url="http://localhost:8080",
        bearer_token="your-keycloak-token"
    )
    client = GCDRestClient(config)
    
    try:
        # First generate a collection
        gcd = client.generate_gcd_collection(137292)
        collection_id = gcd['collection_id']
        logger.info(f"Generated collection: {collection_id}")
        
        # Later, retrieve it
        retrieved = client.get_gcd_collection(collection_id)
        if retrieved:
            logger.info(f"Retrieved collection {collection_id}")
            logger.info(f"  Calibrations: {len(retrieved['calibrations'])}")
            logger.info(f"  Geometry: {len(retrieved['geometry'])}")
        else:
            logger.warning(f"Collection {collection_id} not found")
            
    except APIError as e:
        logger.error(f"Failed: {e}")


if __name__ == "__main__":
    print("GCD REST API Examples")
    print("=" * 50)
    
    # Run examples (comment out as needed)
    # example_1_basic_gcd_generation()
    # example_2_save_gcd_to_file()
    # example_3_get_gcd_summary()
    # example_4_access_gcd_components()
    # example_5_run_specific_data()
    # example_6_batch_operations()
    # example_7_error_handling()
    # example_8_retrieve_previous_collection()
    
    print("\nTo run examples, uncomment them in the main section.")
    print("Make sure the GCD REST API server is running first:")
    print("  cargo run --release")
